In [8]:
import numpy

def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    crossover_point = numpy.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        parent1_idx = k%parents.shape[0]
        parent2_idx = (k+1)%parents.shape[0]
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

def mutation(offspring_crossover):
    for idx in range(offspring_crossover.shape[0]):
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

def cal_pop_fitness(equation_inputs, pop):
    fitness = numpy.sum(pop*equation_inputs, axis=1)
    return fitness

def select_mating_pool(pop, fitness, num_parents):
    parents = numpy.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

equation_inputs = [-2.1,2,-3.5,5,-11,4.7]

num_weights = 6
sol_per_pop = 8
num_parents_mating = 4

pop_size = (sol_per_pop,num_weights)
new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
print("Population: ", new_population)

num_generations = 10
for generation in range(num_generations):
    print("Generation : ", generation)
    fitness = cal_pop_fitness(equation_inputs, new_population)
    parents = select_mating_pool(new_population, fitness, num_parents_mating)
    offspring_crossover = crossover(parents, offspring_size=(pop_size[0]-parents.shape[0], num_weights))
    offspring_mutation = mutation(offspring_crossover)
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation

    print("Best result : ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))

fitness = cal_pop_fitness(equation_inputs, new_population)
best_match_idx = numpy.where(fitness == numpy.max(fitness))

print("Best solution : ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])

Population:  [[-2.19408994 -1.95828235  0.91866589  2.28982426 -1.48893027 -2.96242562]
 [ 3.57753692 -1.08273892  1.44570183  0.23772617 -3.58122027  0.68375841]
 [-0.49045697 -2.42320908  3.9289079   0.05548268 -1.37759142 -1.73372606]
 [ 1.53299144  0.03441828  3.98914879  2.81270846 -1.04244667  2.10498133]
 [ 1.19621627  1.64086778  1.22066915 -3.51831842  2.990098    3.38790544]
 [-2.29452032 -0.11416133  3.1491484   1.17252419 -1.99669801  3.06939127]
 [ 3.90021117 -3.47585372 -0.7609058   0.00518152 -2.04024483  1.95131381]
 [-0.08489492 -3.44493605  0.5477205   3.83854763 -2.12863409  2.98512892]]
Generation :  0
Best result :  48.009204582924596
Generation :  1
Best result :  60.11918923157756
Generation :  2
Best result :  60.11918923157756
Generation :  3
Best result :  64.05614659319846
Generation :  4
Best result :  72.3081812722142
Generation :  5
Best result :  72.3081812722142
Generation :  6
Best result :  77.52019006391367
Generation :  7
Best result :  87.9943078103